# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checklish.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CheckList(object):
    

    _id = -1 
    l_Recon = [] # list of recon check box 
    l_Manual_Check= [] # list of manual check box 
    l_Access_Control = [] # list of a c check box 
    l_C_V_Vulnerability = []  # list of cvv check box 
    l_Risky_Funcktionality = [] # list of lrf check box 
    def setupUi(self, Form):
        
        #----------------SOL_CODE_BUG1234----------------------
        self.l_Recon = [] # list of recon check box 
        self.l_Manual_Check= [] # list of manual check box 
        self.l_Access_Control = [] # list of a c check box 
        self.l_C_V_Vulnerability = []  # list of cvv check box 
        self.l_Risky_Funcktionality = [] # list of lrf check box 
        #------------------------------------------------------
        Form.setObjectName("Form")
        Form.resize(1300, 720)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(667, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setStyleSheet("QLabel     {\n"
"font-weight: bold;\n"
"font-size:16px;\n"
"color: rgb(32, 74, 135);\n"
"}\n"
"QScrollArea {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.Recon = QtWidgets.QWidget()
        self.Recon.setObjectName("Recon")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Recon)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.Recon)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_2 = QtWidgets.QFrame(self.Recon)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RR = QtWidgets.QCheckBox(self.Recon)
        self.RR.setObjectName("RR")
        self.verticalLayout.addWidget(self.RR)
        self.RR_2 = QtWidgets.QCheckBox(self.Recon)
        self.RR_2.setObjectName("RR_2")
        self.verticalLayout.addWidget(self.RR_2)
        self.RR_3 = QtWidgets.QCheckBox(self.Recon)
        self.RR_3.setObjectName("RR_3")
        self.verticalLayout.addWidget(self.RR_3)
        self.RR_4 = QtWidgets.QCheckBox(self.Recon)
        self.RR_4.setObjectName("RR_4")
        self.verticalLayout.addWidget(self.RR_4)
        self.RR_5 = QtWidgets.QCheckBox(self.Recon)
        self.RR_5.setObjectName("RR_5")
        self.verticalLayout.addWidget(self.RR_5)
        self.RR_6 = QtWidgets.QCheckBox(self.Recon)
        self.RR_6.setObjectName("RR_6")
        self.verticalLayout.addWidget(self.RR_6)
        self.label_2 = QtWidgets.QLabel(self.Recon)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line_5 = QtWidgets.QFrame(self.Recon)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.RR_7 = QtWidgets.QCheckBox(self.Recon)
        self.RR_7.setObjectName("RR_7")
        self.verticalLayout.addWidget(self.RR_7)
        self.RR_8 = QtWidgets.QCheckBox(self.Recon)
        self.RR_8.setObjectName("RR_8")
        self.verticalLayout.addWidget(self.RR_8)
        self.RR_9 = QtWidgets.QCheckBox(self.Recon)
        self.RR_9.setObjectName("RR_9")
        self.verticalLayout.addWidget(self.RR_9)
        self.RR_10 = QtWidgets.QCheckBox(self.Recon)
        self.RR_10.setObjectName("RR_10")
        self.verticalLayout.addWidget(self.RR_10)
        self.RR_11 = QtWidgets.QCheckBox(self.Recon)
        self.RR_11.setObjectName("RR_11")
        self.verticalLayout.addWidget(self.RR_11)
        self.RR_12 = QtWidgets.QCheckBox(self.Recon)
        self.RR_12.setObjectName("RR_12")
        self.verticalLayout.addWidget(self.RR_12)
        self.RR_13 = QtWidgets.QCheckBox(self.Recon)
        self.RR_13.setObjectName("RR_13")
        self.verticalLayout.addWidget(self.RR_13)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.Recon)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.line_4 = QtWidgets.QFrame(self.Recon)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.RR_14 = QtWidgets.QCheckBox(self.Recon)
        self.RR_14.setObjectName("RR_14")
        self.verticalLayout_6.addWidget(self.RR_14)
        self.RR_15 = QtWidgets.QCheckBox(self.Recon)
        self.RR_15.setObjectName("RR_15")
        self.verticalLayout_6.addWidget(self.RR_15)
        self.RR_16 = QtWidgets.QCheckBox(self.Recon)
        self.RR_16.setObjectName("RR_16")
        self.verticalLayout_6.addWidget(self.RR_16)
        self.RR_17 = QtWidgets.QCheckBox(self.Recon)
        self.RR_17.setObjectName("RR_17")
        self.verticalLayout_6.addWidget(self.RR_17)
        self.RR_18 = QtWidgets.QCheckBox(self.Recon)
        self.RR_18.setObjectName("RR_18")
        self.verticalLayout_6.addWidget(self.RR_18)
        self.RR_19 = QtWidgets.QCheckBox(self.Recon)
        self.RR_19.setObjectName("RR_19")
        self.verticalLayout_6.addWidget(self.RR_19)
        self.RR_20 = QtWidgets.QCheckBox(self.Recon)
        self.RR_20.setObjectName("RR_20")
        self.verticalLayout_6.addWidget(self.RR_20)
        self.RR_21 = QtWidgets.QCheckBox(self.Recon)
        self.RR_21.setObjectName("RR_21")
        self.verticalLayout_6.addWidget(self.RR_21)
        self.RR_22 = QtWidgets.QCheckBox(self.Recon)
        self.RR_22.setObjectName("RR_22")
        self.verticalLayout_6.addWidget(self.RR_22)
        self.RR_23 = QtWidgets.QCheckBox(self.Recon)
        self.RR_23.setObjectName("RR_23")
        self.verticalLayout_6.addWidget(self.RR_23)
        self.RR_24 = QtWidgets.QCheckBox(self.Recon)
        self.RR_24.setObjectName("RR_24")
        self.verticalLayout_6.addWidget(self.RR_24)
        self.RR_25 = QtWidgets.QCheckBox(self.Recon)
        self.RR_25.setObjectName("RR_25")
        self.verticalLayout_6.addWidget(self.RR_25)
        self.RR_26 = QtWidgets.QCheckBox(self.Recon)
        self.RR_26.setObjectName("RR_26")
        self.verticalLayout_6.addWidget(self.RR_26)
        self.RR_27 = QtWidgets.QCheckBox(self.Recon)
        self.RR_27.setObjectName("RR_27")


        self.verticalLayout_6.addWidget(self.RR_27)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.Recon, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_9.addWidget(self.line_3)
        self.MC_13 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_13.setObjectName("MC_13")
        self.verticalLayout_9.addWidget(self.MC_13)
        self.MC_14 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_14.setObjectName("MC_14")
        self.verticalLayout_9.addWidget(self.MC_14)
        self.MC_15 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_15.setObjectName("MC_15")
        self.verticalLayout_9.addWidget(self.MC_15)
        self.MC_16 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_16.setObjectName("MC_16")
        self.verticalLayout_9.addWidget(self.MC_16)
        self.MC_17 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_17.setObjectName("MC_17")
        self.verticalLayout_9.addWidget(self.MC_17)
        self.MC_18 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_18.setObjectName("MC_18")
        self.verticalLayout_9.addWidget(self.MC_18)
        self.MC_19 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_19.setObjectName("MC_19")
        self.verticalLayout_9.addWidget(self.MC_19)
        self.MC_20 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_20.setObjectName("MC_20")
        self.verticalLayout_9.addWidget(self.MC_20)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 0, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 201, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 2, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_8.addWidget(self.line)
        self.MC = QtWidgets.QCheckBox(self.tab_3)
        self.MC.setObjectName("MC")
        self.verticalLayout_8.addWidget(self.MC)
        self.MC_2 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_2.setObjectName("MC_2")
        self.verticalLayout_8.addWidget(self.MC_2)
        self.MC_3 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_3.setObjectName("MC_3")
        self.verticalLayout_8.addWidget(self.MC_3)
        self.MC_4 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_4.setObjectName("MC_4")
        self.verticalLayout_8.addWidget(self.MC_4)
        self.MC_5 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_5.setObjectName("MC_5")
        self.verticalLayout_8.addWidget(self.MC_5)
        self.MC_6 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_6.setObjectName("MC_6")
        self.verticalLayout_8.addWidget(self.MC_6)
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.line_7 = QtWidgets.QFrame(self.tab_3)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_8.addWidget(self.line_7)
        self.MC_7 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_7.setObjectName("MC_7")
        self.verticalLayout_8.addWidget(self.MC_7)
        self.MC_8 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_8.setObjectName("MC_8")
        self.verticalLayout_8.addWidget(self.MC_8)
        self.MC_9 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_9.setObjectName("MC_9")
        self.verticalLayout_8.addWidget(self.MC_9)
        self.MC_10 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_10.setObjectName("MC_10")
        self.verticalLayout_8.addWidget(self.MC_10)
        self.MC_11 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_11.setObjectName("MC_11")
        self.verticalLayout_8.addWidget(self.MC_11)
        self.MC_12 = QtWidgets.QCheckBox(self.tab_3)
        self.MC_12.setObjectName("MC_12")
        self.verticalLayout_8.addWidget(self.MC_12)
        self.gridLayout_2.addLayout(self.verticalLayout_8, 0, 0, 2, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -173, 829, 661))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.test_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        #font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.test_10.setFont(font)
        self.test_10.setStyleSheet("font-weight: bold;\n"
"font-size:16px;\n"
"color: rgb(32, 74, 135);")
        self.test_10.setObjectName("test_10")
        self.verticalLayout_11.addWidget(self.test_10)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_11.addWidget(self.line_8)
        self.AC = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC.setObjectName("AC")
        self.verticalLayout_11.addWidget(self.AC)
        self.AC_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_2.setObjectName("AC_2")
        self.verticalLayout_11.addWidget(self.AC_2)
        self.AC_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_3.setObjectName("AC_3")
        self.verticalLayout_11.addWidget(self.AC_3)
        self.AC_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_4.setObjectName("AC_4")
        self.verticalLayout_11.addWidget(self.AC_4)
        self.AC_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_5.setObjectName("AC_5")
        self.verticalLayout_11.addWidget(self.AC_5)
        self.AC_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_6.setObjectName("AC_6")
        self.verticalLayout_11.addWidget(self.AC_6)
        self.AC_7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_7.setObjectName("AC_7")
        self.verticalLayout_11.addWidget(self.AC_7)
        self.AC_8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_8.setObjectName("AC_8")
        self.verticalLayout_11.addWidget(self.AC_8)
        self.AC_9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_9.setObjectName("AC_9")
        self.verticalLayout_11.addWidget(self.AC_9)
        self.AC_10 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_10.setObjectName("AC_10")
        self.verticalLayout_11.addWidget(self.AC_10)
        self.AC_11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_11.setObjectName("AC_11")
        self.verticalLayout_11.addWidget(self.AC_11)
        self.AC_12 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_12.setObjectName("AC_12")
        self.verticalLayout_11.addWidget(self.AC_12)
        self.AC_13 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_13.setObjectName("AC_13")
        self.verticalLayout_11.addWidget(self.AC_13)
        self.AC_14 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_14.setObjectName("AC_14")
        self.verticalLayout_11.addWidget(self.AC_14)
        self.AC_15 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_15.setObjectName("AC_15")
        self.verticalLayout_11.addWidget(self.AC_15)
        self.AC_16 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_16.setObjectName("AC_16")
        self.verticalLayout_11.addWidget(self.AC_16)
        self.AC_17 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_17.setObjectName("AC_17")
        self.verticalLayout_11.addWidget(self.AC_17)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setMinimumSize(QtCore.QSize(0, 0))
        self.label_13.setMaximumSize(QtCore.QSize(10221152, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        #font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font-weight: bold;\n"
"font-size:16px;\n"
"color: rgb(32, 74, 135);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_13.addWidget(self.label_13)
        self.line_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_13.addWidget(self.line_13)
        self.AC_18 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_18.setObjectName("AC_18")
        self.verticalLayout_13.addWidget(self.AC_18)
        self.AC_19 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_19.setObjectName("AC_19")
        self.verticalLayout_13.addWidget(self.AC_19)
        self.AC_20 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_20.setObjectName("AC_20")
        self.verticalLayout_13.addWidget(self.AC_20)
        self.AC_21 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_21.setObjectName("AC_21")
        self.verticalLayout_13.addWidget(self.AC_21)
        self.AC_22 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_22.setObjectName("AC_22")
        self.verticalLayout_13.addWidget(self.AC_22)
        self.AC_23 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_23.setObjectName("AC_23")
        self.verticalLayout_13.addWidget(self.AC_23)
        self.AC_24 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_24.setObjectName("AC_24")
        self.verticalLayout_13.addWidget(self.AC_24)
        self.AC_25 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_25.setObjectName("AC_25")
        self.verticalLayout_13.addWidget(self.AC_25)
        self.AC_26 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_26.setObjectName("AC_26")
        self.verticalLayout_13.addWidget(self.AC_26)
        self.AC_27 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_27.setObjectName("AC_27")
        self.verticalLayout_13.addWidget(self.AC_27)
        self.AC_28 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_28.setObjectName("AC_28")
        self.verticalLayout_13.addWidget(self.AC_28)
        self.AC_29 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_29.setObjectName("AC_29")
        self.verticalLayout_13.addWidget(self.AC_29)
        self.AC_30 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_30.setObjectName("AC_30")
        self.verticalLayout_13.addWidget(self.AC_30)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setStyleSheet("font-weight: bold;\n"
"font-size:16px;\n"
"color: rgb(32, 74, 135);")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.label_14)
        self.line_14 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.verticalLayout_13.addWidget(self.line_14)
        self.AC_31 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_31.setObjectName("AC_31")
        self.verticalLayout_13.addWidget(self.AC_31)
        self.AC_32 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_32.setObjectName("AC_32")
        self.verticalLayout_13.addWidget(self.AC_32)
        self.AC_33 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_33.setObjectName("AC_33")
        self.verticalLayout_13.addWidget(self.AC_33)
        self.AC_34 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_34.setObjectName("AC_34")
        self.verticalLayout_13.addWidget(self.AC_34)
        self.AC_35 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.AC_35.setObjectName("AC_35")
        self.verticalLayout_13.addWidget(self.AC_35)
        self.horizontalLayout_3.addLayout(self.verticalLayout_13)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_5)
        self.scrollArea_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 838, 619))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        #font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("font-weight: bold;\n"
"font-size:16px;\n"
"color: rgb(32, 74, 135);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_15.addWidget(self.label_15)
        self.line_15 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_15.addWidget(self.line_15)
        self.VUL = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL.setObjectName("VUL")
        self.verticalLayout_15.addWidget(self.VUL)
        self.VUL_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_2.setObjectName("VUL_2")
        self.verticalLayout_15.addWidget(self.VUL_2)
        self.VUL_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_3.setObjectName("VUL_3")
        self.verticalLayout_15.addWidget(self.VUL_3)
        self.VUL_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_4.setObjectName("VUL_4")
        self.verticalLayout_15.addWidget(self.VUL_4)
        self.VUL_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_5.setObjectName("VUL_5")
        self.verticalLayout_15.addWidget(self.VUL_5)
        self.VUL_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_6.setObjectName("VUL_6")
        self.verticalLayout_15.addWidget(self.VUL_6)
        self.VUL_7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_7.setObjectName("VUL_7")
        self.verticalLayout_15.addWidget(self.VUL_7)
        self.VUL_8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_8.setObjectName("VUL_8")
        self.verticalLayout_15.addWidget(self.VUL_8)
        self.VUL_9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_9.setObjectName("VUL_9")
        self.verticalLayout_15.addWidget(self.VUL_9)
        self.VUL_10 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_10.setObjectName("VUL_10")
        self.verticalLayout_15.addWidget(self.VUL_10)
        self.VUL_11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_11.setObjectName("VUL_11")
        self.verticalLayout_15.addWidget(self.VUL_11)
        self.VUL_12 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_12.setObjectName("VUL_12")
        self.verticalLayout_15.addWidget(self.VUL_12)
        self.VUL_13 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_13.setObjectName("VUL_13")
        self.verticalLayout_15.addWidget(self.VUL_13)
        self.VUL_14 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_14.setObjectName("VUL_14")
        self.verticalLayout_15.addWidget(self.VUL_14)
        self.VUL_15 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_15.setObjectName("VUL_15")
        self.verticalLayout_15.addWidget(self.VUL_15)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.line_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.horizontalLayout_4.addWidget(self.line_17)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 12))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_16.addWidget(self.label_16)
        self.VUL_16 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_16.setObjectName("VUL_16")
        self.verticalLayout_16.addWidget(self.VUL_16)
        self.VUL_17 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_17.setObjectName("VUL_17")
        self.verticalLayout_16.addWidget(self.VUL_17)
        self.VUL_18 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_18.setObjectName("VUL_18")
        self.verticalLayout_16.addWidget(self.VUL_18)
        self.VUL_19 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_19.setObjectName("VUL_19")
        self.verticalLayout_16.addWidget(self.VUL_19)
        self.VUL_20 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_20.setObjectName("VUL_20")
        self.verticalLayout_16.addWidget(self.VUL_20)
        self.VUL_21 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_21.setObjectName("VUL_21")
        self.verticalLayout_16.addWidget(self.VUL_21)
        self.VUL_22 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_22.setObjectName("VUL_22")
        self.verticalLayout_16.addWidget(self.VUL_22)
        self.VUL_23 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_23.setObjectName("VUL_23")
        self.verticalLayout_16.addWidget(self.VUL_23)
        self.VUL_24 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_24.setObjectName("VUL_24")
        self.verticalLayout_16.addWidget(self.VUL_24)
        self.VUL_25 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_25.setObjectName("VUL_25")
        self.verticalLayout_16.addWidget(self.VUL_25)
        self.VUL_26 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_26.setObjectName("VUL_26")
        self.verticalLayout_16.addWidget(self.VUL_26)
        self.VUL_27 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_27.setObjectName("VUL_27")
        self.verticalLayout_16.addWidget(self.VUL_27)
        self.VUL_28 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_28.setObjectName("VUL_28")
        self.verticalLayout_16.addWidget(self.VUL_28)
        self.VUL_29 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_29.setObjectName("VUL_29")
        self.verticalLayout_16.addWidget(self.VUL_29)
        self.VUL_30 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_30.setObjectName("VUL_30")
        self.verticalLayout_16.addWidget(self.VUL_30)
        self.horizontalLayout_4.addLayout(self.verticalLayout_16)
        self.line_18 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.horizontalLayout_4.addWidget(self.line_18)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.VUL_31 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_31.setObjectName("VUL_31")
        self.verticalLayout_17.addWidget(self.VUL_31)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_17.setStyleSheet("font-weight: bold;\n"
"font-size:16px;\n"
"color: rgb(32, 74, 135);")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_17.addWidget(self.label_17)
        self.line_19 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.verticalLayout_17.addWidget(self.line_19)
        self.VUL_32 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_32.setObjectName("VUL_32")
        self.verticalLayout_17.addWidget(self.VUL_32)
        self.VUL_33 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_33.setObjectName("VUL_33")
        self.verticalLayout_17.addWidget(self.VUL_33)
        self.VUL_34 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_34.setObjectName("VUL_34")
        self.verticalLayout_17.addWidget(self.VUL_34)
        self.VUL_35 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_35.setObjectName("VUL_35")
        self.verticalLayout_17.addWidget(self.VUL_35)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_18.setStyleSheet("font-weight: bold;\n"
"font-size:16px;\n"
"color: rgb(32, 74, 135);")
        self.label_18.setObjectName("label_18")
        self.verticalLayout_17.addWidget(self.label_18)
        self.line_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_17.addWidget(self.line_16)
        self.VUL_36 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_36.setObjectName("VUL_36")
        self.verticalLayout_17.addWidget(self.VUL_36)
        self.VUL_37 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_37.setObjectName("VUL_37")
        self.verticalLayout_17.addWidget(self.VUL_37)
        self.VUL_38 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_38.setObjectName("VUL_38")
        self.verticalLayout_17.addWidget(self.VUL_38)
        self.VUL_39 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_39.setObjectName("VUL_39")
        self.verticalLayout_17.addWidget(self.VUL_39)
        self.VUL_40 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_40.setObjectName("VUL_40")
        self.verticalLayout_17.addWidget(self.VUL_40)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_19.setStyleSheet("font-weight: bold;\n"
"font-size:16px;\n"
"color: rgb(32, 74, 135);")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_17.addWidget(self.label_19)
        self.line_20 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.verticalLayout_17.addWidget(self.line_20)
        self.VUL_41 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_41.setObjectName("VUL_41")
        self.verticalLayout_17.addWidget(self.VUL_41)
        self.VUL_42 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_42.setObjectName("VUL_42")
        self.verticalLayout_17.addWidget(self.VUL_42)
        self.VUL_43 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_43.setObjectName("VUL_43")
        self.verticalLayout_17.addWidget(self.VUL_43)
        self.VUL_44 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_44.setObjectName("VUL_44")
        self.verticalLayout_17.addWidget(self.VUL_44)
        self.VUL_45 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_4)
        self.VUL_45.setObjectName("VUL_45")
        self.verticalLayout_17.addWidget(self.VUL_45)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_17)
        self.verticalLayout_18.addLayout(self.horizontalLayout_4)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_4.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_19.addWidget(self.label_20)
        self.line_21 = QtWidgets.QFrame(self.tab_2)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.verticalLayout_19.addWidget(self.line_21)
        self.RF = QtWidgets.QCheckBox(self.tab_2)
        self.RF.setObjectName("RF")
        self.verticalLayout_19.addWidget(self.RF)
        self.RF_2 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_2.setObjectName("RF_2")
        self.verticalLayout_19.addWidget(self.RF_2)
        self.RF_3 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_3.setObjectName("RF_3")
        self.verticalLayout_19.addWidget(self.RF_3)
        self.RF_4 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_4.setObjectName("RF_4")
        self.verticalLayout_19.addWidget(self.RF_4)
        self.RF_5 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_5.setObjectName("RF_5")
        self.verticalLayout_19.addWidget(self.RF_5)
        self.RF_6 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_6.setObjectName("RF_6")
        self.verticalLayout_19.addWidget(self.RF_6)
        self.RF_7 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_7.setObjectName("RF_7")
        self.verticalLayout_19.addWidget(self.RF_7)
        self.RF_8 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_8.setObjectName("RF_8")
        self.verticalLayout_19.addWidget(self.RF_8)
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_19.addWidget(self.label_6)
        self.RF_9 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_9.setObjectName("RF_9")
        self.verticalLayout_19.addWidget(self.RF_9)
        self.RF_10 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_10.setObjectName("RF_10")
        self.verticalLayout_19.addWidget(self.RF_10)
        self.RF_11 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_11.setObjectName("RF_11")
        self.verticalLayout_19.addWidget(self.RF_11)
        self.RF_12 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_12.setObjectName("RF_12")
        self.verticalLayout_19.addWidget(self.RF_12)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem7)
        self.horizontalLayout_5.addLayout(self.verticalLayout_19)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.line_6 = QtWidgets.QFrame(self.tab_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_10.addWidget(self.line_6)
        self.RF_13 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_13.setObjectName("RF_13")
        self.verticalLayout_10.addWidget(self.RF_13)
        self.RF_14 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_14.setObjectName("RF_14")
        self.verticalLayout_10.addWidget(self.RF_14)
        self.RF_15 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_15.setObjectName("RF_15")
        self.verticalLayout_10.addWidget(self.RF_15)
        self.RF_16 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_16.setObjectName("RF_16")
        self.verticalLayout_10.addWidget(self.RF_16)
        self.RF_17 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_17.setObjectName("RF_17")
        self.verticalLayout_10.addWidget(self.RF_17)
        self.RF_18 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_18.setObjectName("RF_18")
        self.verticalLayout_10.addWidget(self.RF_18)
        self.RF_19 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_19.setObjectName("RF_19")
        self.verticalLayout_10.addWidget(self.RF_19)
        self.RF_20 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_20.setObjectName("RF_20")
        self.verticalLayout_10.addWidget(self.RF_20)
        self.RF_21 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_21.setObjectName("RF_21")
        self.verticalLayout_10.addWidget(self.RF_21)
        self.RF_22 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_22.setObjectName("RF_22")
        self.verticalLayout_10.addWidget(self.RF_22)
        self.RF_23 = QtWidgets.QCheckBox(self.tab_2)
        self.RF_23.setObjectName("RF_23")
        self.verticalLayout_10.addWidget(self.RF_23)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)


        ##add all check box to list 

        self.prepare_all()


        #code to center the widget 
        fg = self.frameGeometry()
        cp = QtWidgets.QDesktopWidget().availableGeometry().center()
        fg.moveCenter(cp)
        self.move(fg.topLeft())


        #the firest is recon remember that 
        


        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "check liste"))
        self.pushButton_2.setText(_translate("Form", "cancel"))
        self.pushButton.setText(_translate("Form", "save"))
        self.pushButton_2.setShortcut(_translate("Form", "Esc"))
        self.pushButton.setShortcut(_translate("Form", "Return"))
        self.label.setText(_translate("Form", "Recon on wildcard domain"))
        self.RR.setText(_translate("Form", "Run Amass"))
        self.RR_2.setText(_translate("Form", "Run Subfinder"))
        self.RR_3.setText(_translate("Form", "Run Rapid7 FDNS"))
        self.RR_4.setText(_translate("Form", "Use commonspeak2 list"))
        self.RR_5.setText(_translate("Form", "Run massdns"))
        self.RR_6.setText(_translate("Form", "Run altdns"))
        self.label_2.setText(_translate("Form", "Scanning"))
        self.RR_7.setText(_translate("Form", " Arachni Scan"))
        self.RR_8.setText(_translate("Form", "Owasp ZAp Scan"))
        self.RR_9.setText(_translate("Form", " Burp Spider"))
        self.RR_10.setText(_translate("Form", "Wayback machine"))
        self.RR_11.setText(_translate("Form", "Linkfinder"))
        self.RR_12.setText(_translate("Form", "Burp Scanning"))
        self.RR_13.setText(_translate("Form", "Url with Android application"))
        self.label_3.setText(_translate("Form", "Information Gathering"))
        self.RR_14.setText(_translate("Form", "Manually explore the site"))
        self.RR_15.setText(_translate("Form", "Spider/crawl for missed or hidden content"))
        self.RR_16.setText(_translate("Form", "Check for files that expose content, such as robots.txt, sitemap.xml, .DS_Store"))
        self.RR_17.setText(_translate("Form", "Check the caches of major search engines for publicly accessible sites"))
        self.RR_18.setText(_translate("Form", "Check for differences in content based on User Agent "))
        self.RR_19.setText(_translate("Form", "Perform Web Application Fingerprinting"))
        self.RR_20.setText(_translate("Form", "Identify technologies used"))
        self.RR_21.setText(_translate("Form", "Identify user roles"))
        self.RR_22.setText(_translate("Form", "Identify client-side code"))
        self.RR_23.setText(_translate("Form", "Identify multiple versions/channels (e.g. web, mobile web, mobile app)"))
        self.RR_24.setText(_translate("Form", "Identify co-hosted and related applications"))
        self.RR_25.setText(_translate("Form", "Identify all hostnames and ports"))
        self.RR_26.setText(_translate("Form", "Identify third-party hosted content"))
        self.RR_27.setText(_translate("Form", "Identify Debug parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Recon), _translate("Form", "Recon"))
        self.label_5.setText(_translate("Form", "Configuration Management"))
        self.MC_13.setText(_translate("Form", " Check for commonly used application and administrative URLs"))
        self.MC_14.setText(_translate("Form", " Check for old, backup and unreferenced files"))
        self.MC_15.setText(_translate("Form", "Check HTTP methods supported and Cross Site Tracing (XST)"))
        self.MC_16.setText(_translate("Form", "Test file extensions handling"))
        self.MC_17.setText(_translate("Form", "Test for security HTTP headers (e.g. CSP, X-Frame-Options, HSTS)"))
        self.MC_18.setText(_translate("Form", "Test for policies (e.g. Flash, Silverlight, robots)"))
        self.MC_19.setText(_translate("Form", "Test for non-production data in live environment, and vice-versa"))
        self.MC_20.setText(_translate("Form", "Check for sensitive data in client-side code (e.g. API keys, credentials)"))
        self.label_4.setText(_translate("Form", "Manual checking"))
        self.MC.setText(_translate("Form", "Shodan"))
        self.MC_2.setText(_translate("Form", "Censys"))
        self.MC_3.setText(_translate("Form", " Google dorks"))
        self.MC_4.setText(_translate("Form", "Pastebin"))
        self.MC_5.setText(_translate("Form", "Github"))
        self.MC_6.setText(_translate("Form", "OSINT"))
        self.label_7.setText(_translate("Form", "Secure Transmission"))
        self.MC_7.setText(_translate("Form", "Check SSL Version, Algorithms, Key length"))
        self.MC_8.setText(_translate("Form", "Check for Digital Certificate Validity (Duration, \n"
"Signature and CN)"))
        self.MC_9.setText(_translate("Form", "Check credentials only delivered over HTTPS"))
        self.MC_10.setText(_translate("Form", "Check that the login form is delivered over\n"
"HTTPS"))
        self.MC_11.setText(_translate("Form", "Check session tokens only delivered over\n"
"HTTPS"))
        self.MC_12.setText(_translate("Form", "Check if HTTP Strict Transport Security\n"
" (HSTS) in use"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Manual check"))
        self.test_10.setText(_translate("Form", "Authentication"))
        self.AC.setText(_translate("Form", "Test for user enumeration"))
        self.AC_2.setText(_translate("Form", "Test for authentication bypass"))
        self.AC_3.setText(_translate("Form", "Test for bruteforce protection"))
        self.AC_4.setText(_translate("Form", "Test password quality rules"))
        self.AC_5.setText(_translate("Form", "Test remember me functionality"))
        self.AC_6.setText(_translate("Form", "Test for autocomplete on password forms/input"))
        self.AC_7.setText(_translate("Form", "Test password reset and/or recovery"))
        self.AC_8.setText(_translate("Form", "Test password change process"))
        self.AC_9.setText(_translate("Form", "Test CAPTCHA"))
        self.AC_10.setText(_translate("Form", "Test multi factor authentication"))
        self.AC_11.setText(_translate("Form", "Test for logout functionality presence"))
        self.AC_12.setText(_translate("Form", "Test for cache management on \n"
"HTTP (eg Pragma, Expires, Max-age)"))
        self.AC_13.setText(_translate("Form", "Test for default logins"))
        self.AC_14.setText(_translate("Form", "Test for user-accessible authentication history"))
        self.AC_15.setText(_translate("Form", "Test for out-of channel notification of account \n"
"lockouts and successful password changes\n"
""))
        self.AC_16.setText(_translate("Form", "Test for consistent authentication across \n"
"applications with shared authentication schema / SSO"))
        self.AC_17.setText(_translate("Form", "Test for user-accessible authentication history"))
        self.label_13.setText(_translate("Form", "Session Management"))
        self.AC_18.setText(_translate("Form", "Establish how session management is handled in \n"
"the application (eg, tokens in \n"
"cookies, token in URL)"))
        self.AC_19.setText(_translate("Form", "Check session tokens for cookie flags (httpOnly and secure)"))
        self.AC_20.setText(_translate("Form", "Check session cookie scope (path and domain)"))
        self.AC_21.setText(_translate("Form", "Check session cookie duration (expires and max-age)"))
        self.AC_22.setText(_translate("Form", "Check session termination after a maximum lifetime"))
        self.AC_23.setText(_translate("Form", "Check session termination after relative timeout"))
        self.AC_24.setText(_translate("Form", "Check session termination after logout"))
        self.AC_25.setText(_translate("Form", " Test to see if users can have multiple simultaneous sessions"))
        self.AC_26.setText(_translate("Form", "Test session cookies for randomness"))
        self.AC_27.setText(_translate("Form", "Confirm that new session tokens are issued on login, \n"
"role change and logout"))
        self.AC_28.setText(_translate("Form", "Test for consistent session management across applications\n"
" with shared session management"))
        self.AC_29.setText(_translate("Form", "Test for session puzzling"))
        self.AC_30.setText(_translate("Form", "Test for CSRF and clickjacking"))
        self.label_14.setText(_translate("Form", "Authorization"))
        self.AC_31.setText(_translate("Form", "Test for path traversal"))
        self.AC_32.setText(_translate("Form", "Test for bypassing authorization schema"))
        self.AC_33.setText(_translate("Form", "Test for vertical Access control problems "))
        self.AC_34.setText(_translate("Form", "Test for horizontal Access control problems"))
        self.AC_35.setText(_translate("Form", "Test for missing authorization"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Access control "))
        self.label_15.setText(_translate("Form", "Data Validation"))
        self.VUL.setText(_translate("Form", "Test for Reflected Cross Site Scripting"))
        self.VUL_2.setText(_translate("Form", "Test for Stored Cross Site Scripting"))
        self.VUL_3.setText(_translate("Form", "Test for DOM based Cross Site Scripting"))
        self.VUL_4.setText(_translate("Form", "Test for Cross Site Flashing"))
        self.VUL_5.setText(_translate("Form", "Test for HTML Injection"))
        self.VUL_6.setText(_translate("Form", "Test for SQL Injection"))
        self.VUL_7.setText(_translate("Form", "Test for LDAP Injection"))
        self.VUL_8.setText(_translate("Form", "Test for ORM Injection"))
        self.VUL_9.setText(_translate("Form", "Test for XML Injection"))
        self.VUL_10.setText(_translate("Form", "Test for XXE Injection"))
        self.VUL_11.setText(_translate("Form", "Test for SSI Injection"))
        self.VUL_12.setText(_translate("Form", "Test for XPath Injection"))
        self.VUL_13.setText(_translate("Form", "Test for XQuery Injection"))
        self.VUL_14.setText(_translate("Form", "Test for IMAP/SMTP Injection"))
        self.VUL_15.setText(_translate("Form", "Test for Code Injection"))
        self.VUL_16.setText(_translate("Form", "Test for Expression Language\n"
" Injection"))
        self.VUL_17.setText(_translate("Form", "Test for Command Injection"))
        self.VUL_18.setText(_translate("Form", "Test for Overflow (Stack, Heap\n"
" and Integer)"))
        self.VUL_19.setText(_translate("Form", "Test for Format String"))
        self.VUL_20.setText(_translate("Form", "Test for incubated vulnerabilities"))
        self.VUL_21.setText(_translate("Form", "Test for HTTP Splitting/Smuggling"))
        self.VUL_22.setText(_translate("Form", "Test for HTTP Verb Tampering"))
        self.VUL_23.setText(_translate("Form", "Test for Open Redirection"))
        self.VUL_24.setText(_translate("Form", "Test for Local File Inclusion"))
        self.VUL_25.setText(_translate("Form", "Test for Remote File Inclusion"))
        self.VUL_26.setText(_translate("Form", "Compare client-side and server-side\n"
" validation rules"))
        self.VUL_27.setText(_translate("Form", "Test for NoSQL injection"))
        self.VUL_28.setText(_translate("Form", "Test for HTTP parameter pollution"))
        self.VUL_29.setText(_translate("Form", "Test for auto-binding"))
        self.VUL_30.setText(_translate("Form", " Test for Mass Assignment"))
        self.VUL_31.setText(_translate("Form", "Test for NULL/Invalid\n"
" Session Cookie"))
        self.label_17.setText(_translate("Form", "Data Validation"))
        self.VUL_32.setText(_translate("Form", "Test for anti-automation"))
        self.VUL_33.setText(_translate("Form", "Test for account lockout"))
        self.VUL_34.setText(_translate("Form", "Test for HTTP protocol DoS"))
        self.VUL_35.setText(_translate("Form", "Test for SQL wildcard DoS"))
        self.label_18.setText(_translate("Form", "Business Logic"))
        self.VUL_36.setText(_translate("Form", "Test for feature misuse"))
        self.VUL_37.setText(_translate("Form", "Test for lack of non-repudiation"))
        self.VUL_38.setText(_translate("Form", "Test for trust relationships"))
        self.VUL_39.setText(_translate("Form", "Test for integrity of data"))
        self.VUL_40.setText(_translate("Form", "Test segregation of duties"))
        self.label_19.setText(_translate("Form", "Cryptography"))
        self.VUL_41.setText(_translate("Form", "Check if data which should be \n"
"encrypted is not"))
        self.VUL_42.setText(_translate("Form", "Check for wrong algorithms \n"
"usage depending on context"))
        self.VUL_43.setText(_translate("Form", "Check for weak algorithms\n"
" usage"))
        self.VUL_44.setText(_translate("Form", "Check for proper use of salting"))
        self.VUL_45.setText(_translate("Form", "Check for randomness functions"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "C_S Vulnerability"))
        self.label_20.setText(_translate("Form", "Risky Functionality - File Uploads"))
        self.RF.setText(_translate("Form", "Test that acceptable file types are whitelisted"))
        self.RF_2.setText(_translate("Form", "Test that file size limits, upload frequency and total\n"
"file counts are defined and are enforced"))
        self.RF_3.setText(_translate("Form", "Test that file contents match the defined file type"))
        self.RF_4.setText(_translate("Form", "Test that all file uploads have Anti-Virus scanning in-place."))
        self.RF_5.setText(_translate("Form", "Test that unsafe filenames are sanitised"))
        self.RF_6.setText(_translate("Form", "Test that uploaded files are not directly accessible within\n"
"the web root"))
        self.RF_7.setText(_translate("Form", "Test that uploaded files are not served on the \n"
"same hostname/port"))
        self.RF_8.setText(_translate("Form", "Test that files and other media are integrated with \n"
"the authentication and authorisation schemas"))
        self.label_6.setText(_translate("Form", "HTML 5"))
        self.RF_9.setText(_translate("Form", "Test Web Messaging"))
        self.RF_10.setText(_translate("Form", "Test for Web Storage SQL injection"))
        self.RF_11.setText(_translate("Form", "Check CORS implementation"))
        self.RF_12.setText(_translate("Form", "Check Offline Web Application"))
        self.label_9.setText(_translate("Form", "Risky Functionality - Card Payment"))
        self.RF_13.setText(_translate("Form", "Test for known vulnerabilities and configuration issues\n"
" on Web Server and Web Application"))
        self.RF_14.setText(_translate("Form", "Test for default or guessable password"))
        self.RF_15.setText(_translate("Form", "Test for non-production data in live environment,\n"
" and vice-versa"))
        self.RF_16.setText(_translate("Form", "Test for Injection vulnerabilities"))
        self.RF_17.setText(_translate("Form", "Test for Buffer Overflows"))
        self.RF_18.setText(_translate("Form", "Test for Insecure Cryptographic Storage"))
        self.RF_19.setText(_translate("Form", "Test for Insufficient Transport Layer Protection"))
        self.RF_20.setText(_translate("Form", "Test for Improper Error Handling"))
        self.RF_21.setText(_translate("Form", "Test for all vulnerabilities with a CVSS v2 score > 4.0"))
        self.RF_22.setText(_translate("Form", "Test for Authentication and Authorization issues"))
        self.RF_23.setText(_translate("Form", "Test for CSRF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Risky Functionality"))

    def prepare_recon(self) : 
        self.l_Recon.append(self.RR)
        self.l_Recon.append(self.RR_2)
        self.l_Recon.append(self.RR_3)
        self.l_Recon.append(self.RR_4)
        self.l_Recon.append(self.RR_5)
        self.l_Recon.append(self.RR_6)
        self.l_Recon.append(self.RR_7)
        self.l_Recon.append(self.RR_8)
        self.l_Recon.append(self.RR_9)
        self.l_Recon.append(self.RR_10)
        self.l_Recon.append(self.RR_11)
        self.l_Recon.append(self.RR_12)
        self.l_Recon.append(self.RR_13)
        self.l_Recon.append(self.RR_14)
        self.l_Recon.append(self.RR_15)
        self.l_Recon.append(self.RR_16)
        self.l_Recon.append(self.RR_17)
        self.l_Recon.append(self.RR_18)
        self.l_Recon.append(self.RR_19)
        self.l_Recon.append(self.RR_20)
        self.l_Recon.append(self.RR_21)
        self.l_Recon.append(self.RR_22)
        self.l_Recon.append(self.RR_23)
        self.l_Recon.append(self.RR_24)
        self.l_Recon.append(self.RR_25)
        self.l_Recon.append(self.RR_26)
        self.l_Recon.append(self.RR_27)
    def prepare_AC(self):
        self.l_Access_Control.append(self.AC)
        self.l_Access_Control.append(self.AC_2)
        self.l_Access_Control.append(self.AC_3)
        self.l_Access_Control.append(self.AC_4)
        self.l_Access_Control.append(self.AC_5)
        self.l_Access_Control.append(self.AC_6)
        self.l_Access_Control.append(self.AC_7)
        self.l_Access_Control.append(self.AC_8)
        self.l_Access_Control.append(self.AC_9)
        self.l_Access_Control.append(self.AC_10)
        self.l_Access_Control.append(self.AC_11)
        self.l_Access_Control.append(self.AC_12)
        self.l_Access_Control.append(self.AC_13)
        self.l_Access_Control.append(self.AC_14)
        self.l_Access_Control.append(self.AC_15)
        self.l_Access_Control.append(self.AC_16)
        self.l_Access_Control.append(self.AC_17)
        self.l_Access_Control.append(self.AC_18)
        self.l_Access_Control.append(self.AC_19)
        self.l_Access_Control.append(self.AC_20)
        self.l_Access_Control.append(self.AC_21)
        self.l_Access_Control.append(self.AC_22)
        self.l_Access_Control.append(self.AC_23)
        self.l_Access_Control.append(self.AC_24)
        self.l_Access_Control.append(self.AC_25)
        self.l_Access_Control.append(self.AC_26)
        self.l_Access_Control.append(self.AC_27)
        self.l_Access_Control.append(self.AC_28)
        self.l_Access_Control.append(self.AC_29)
        self.l_Access_Control.append(self.AC_30)
        self.l_Access_Control.append(self.AC_31)
        self.l_Access_Control.append(self.AC_32)
        self.l_Access_Control.append(self.AC_33)
        self.l_Access_Control.append(self.AC_34)
        self.l_Access_Control.append(self.AC_35)

    def prepare_mc(self): 
        self.l_Manual_Check.append(self.MC)
        self.l_Manual_Check.append(self.MC_2)
        self.l_Manual_Check.append(self.MC_3)
        self.l_Manual_Check.append(self.MC_4)
        self.l_Manual_Check.append(self.MC_5)
        self.l_Manual_Check.append(self.MC_6)
        self.l_Manual_Check.append(self.MC_7)
        self.l_Manual_Check.append(self.MC_8)
        self.l_Manual_Check.append(self.MC_9)
        self.l_Manual_Check.append(self.MC_10)
        self.l_Manual_Check.append(self.MC_11)
        self.l_Manual_Check.append(self.MC_12)
        self.l_Manual_Check.append(self.MC_13)
        self.l_Manual_Check.append(self.MC_14)
        self.l_Manual_Check.append(self.MC_15)
        self.l_Manual_Check.append(self.MC_16)
        self.l_Manual_Check.append(self.MC_17)
        self.l_Manual_Check.append(self.MC_18)
        self.l_Manual_Check.append(self.MC_19)
        self.l_Manual_Check.append(self.MC_20)
    def prepare_vul(self): 
        self.l_C_V_Vulnerability.append(self.VUL)
        self.l_C_V_Vulnerability.append(self.VUL_2)
        self.l_C_V_Vulnerability.append(self.VUL_3)
        self.l_C_V_Vulnerability.append(self.VUL_4)
        self.l_C_V_Vulnerability.append(self.VUL_5)
        self.l_C_V_Vulnerability.append(self.VUL_6)
        self.l_C_V_Vulnerability.append(self.VUL_7)
        self.l_C_V_Vulnerability.append(self.VUL_8)
        self.l_C_V_Vulnerability.append(self.VUL_9)
        self.l_C_V_Vulnerability.append(self.VUL_10)
        self.l_C_V_Vulnerability.append(self.VUL_11)
        self.l_C_V_Vulnerability.append(self.VUL_12)
        self.l_C_V_Vulnerability.append(self.VUL_13)
        self.l_C_V_Vulnerability.append(self.VUL_14)
        self.l_C_V_Vulnerability.append(self.VUL_15)
        self.l_C_V_Vulnerability.append(self.VUL_16)
        self.l_C_V_Vulnerability.append(self.VUL_17)
        self.l_C_V_Vulnerability.append(self.VUL_18)
        self.l_C_V_Vulnerability.append(self.VUL_19)
        self.l_C_V_Vulnerability.append(self.VUL_20)
        self.l_C_V_Vulnerability.append(self.VUL_21)
        self.l_C_V_Vulnerability.append(self.VUL_22)
        self.l_C_V_Vulnerability.append(self.VUL_23)
        self.l_C_V_Vulnerability.append(self.VUL_24)
        self.l_C_V_Vulnerability.append(self.VUL_25)
        self.l_C_V_Vulnerability.append(self.VUL_26)
        self.l_C_V_Vulnerability.append(self.VUL_27)
        self.l_C_V_Vulnerability.append(self.VUL_28)
        self.l_C_V_Vulnerability.append(self.VUL_29)
        self.l_C_V_Vulnerability.append(self.VUL_30)
        self.l_C_V_Vulnerability.append(self.VUL_31)
        self.l_C_V_Vulnerability.append(self.VUL_32)
        self.l_C_V_Vulnerability.append(self.VUL_33)
        self.l_C_V_Vulnerability.append(self.VUL_34)
        self.l_C_V_Vulnerability.append(self.VUL_35)
        self.l_C_V_Vulnerability.append(self.VUL_36)
        self.l_C_V_Vulnerability.append(self.VUL_37)
        self.l_C_V_Vulnerability.append(self.VUL_38)
        self.l_C_V_Vulnerability.append(self.VUL_39)
        self.l_C_V_Vulnerability.append(self.VUL_40)
        self.l_C_V_Vulnerability.append(self.VUL_41)
        self.l_C_V_Vulnerability.append(self.VUL_42)
        self.l_C_V_Vulnerability.append(self.VUL_43)
        self.l_C_V_Vulnerability.append(self.VUL_44)
        self.l_C_V_Vulnerability.append(self.VUL_45)


    def prepare_rf(self): 
        self.l_Risky_Funcktionality.append(self.RF)
        self.l_Risky_Funcktionality.append(self.RF_2)
        self.l_Risky_Funcktionality.append(self.RF_3)
        self.l_Risky_Funcktionality.append(self.RF_4)
        self.l_Risky_Funcktionality.append(self.RF_5)
        self.l_Risky_Funcktionality.append(self.RF_6)
        self.l_Risky_Funcktionality.append(self.RF_7)
        self.l_Risky_Funcktionality.append(self.RF_8)
        self.l_Risky_Funcktionality.append(self.RF_9)
        self.l_Risky_Funcktionality.append(self.RF_10)
        self.l_Risky_Funcktionality.append(self.RF_11)
        self.l_Risky_Funcktionality.append(self.RF_12)
        self.l_Risky_Funcktionality.append(self.RF_13)
        self.l_Risky_Funcktionality.append(self.RF_14)
        self.l_Risky_Funcktionality.append(self.RF_15)
        self.l_Risky_Funcktionality.append(self.RF_16)
        self.l_Risky_Funcktionality.append(self.RF_17)
        self.l_Risky_Funcktionality.append(self.RF_18)
        self.l_Risky_Funcktionality.append(self.RF_19)
        self.l_Risky_Funcktionality.append(self.RF_20)
        self.l_Risky_Funcktionality.append(self.RF_21)
        self.l_Risky_Funcktionality.append(self.RF_22)
        self.l_Risky_Funcktionality.append(self.RF_23)
    def prepare_all(self) : 
        self.prepare_recon() 
        self.prepare_AC()
        self.prepare_mc() 
        self.prepare_rf() 
        self.prepare_vul()
import icon_rc
